Feature capture tag removal
Greenstand/treetracker-admin-client pull request #1003
Opened 2023-01-08 21:13 UTC by maxt0214

## Description

_[Add a description of the changes]_

**Issue(s) addressed**

- Resolves #issue_number

**What kind of change(s) does this PR introduce?**

- [ ] Enhancement
- [ ] Bug fix
- [ ] Refactor

**Please check if the PR fulfils these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## Issue

**What is the current behavior?**

**What is the new behavior?**

## Breaking change

**Does this PR introduce a breaking change?**

## Other useful information

2023-01-08 21:26 UTC, maxt0214 commented
@nmcharlton For the issue of capture still appears after tag is removed. I believe this is a backend issue. When I restart the frontend over and filter captures by tag 'test 1', the capture that had 'test 1' removed yesterday still appears.

2023-01-09 18:42 UTC, nmcharlton requested changes
Can you take a look at the failing test and see if it's something you're able to fix? `npm run test`

2023-01-09 21:47 UTC, maxt0214 commented on src/context/CaptureDetailContext.js
> +        console.log('All tags: ', tags);
Will do

2023-01-10 04:47 UTC, maxt0214 commented on src/context/CaptureDetailContext.js
> +        console.log('All tags: ', tags);
I have removed this log. Its only a temporary debugging log

2023-01-10 04:48 UTC, maxt0214 commented
@nmcharlton I have fixed the issue and reran the tests. Everything works on local.

2023-01-12 21:15 UTC, nmcharlton approved these changes
Thanks @maxt0214, great work!

2023-01-12 21:15 UTC, merged