feat: refactor capture tagging UX #995
Greenstand/treetracker-admin-client pull request #1014
Opened 2023-01-30 17:05 UTC by rccm88

## Description

_[Add a description of the changes]_

**Issue(s) addressed**

- Resolves #995

**What kind of change(s) does this PR introduce?**

- [ ] Enhancement
- [ ] Bug fix
- [x ] Refactor

**Please check if the PR fulfils these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## Issue

**What is the current behavior?**
When verifying captures, users are forced to select a "capture approval tag" from a fairly arbitrary radio button list.

**What is the new behavior?**
Removal of the radio buttons and an enhancement to the "Additional tags" input to present common tags for quick selection

## Breaking change

**Does this PR introduce a breaking change?**
No

## Other useful information

2023-01-31 21:13 UTC, nmcharlton requested changes
Nice work @rccm88! Just remove the commented out code and we're ready to merge.
For future PRs, it's best to create a new branch in your local fork to work on the issue. That means you can start work on a new issue while waiting for a PR review.

2023-01-31 21:13 UTC, nmcharlton commented on src/components/SidePanel.js
> +/*const CAP_APP_TAG = [
Let's remove the old code rather than just comment it out.

2023-02-03 12:15 UTC, rccm88 commented
> Nice work @rccm88! Just remove the commented out code and we're ready to merge. For future PRs, it's best to create a new branch in your local fork to work on the issue. That means you can start work on a new issue while waiting for a PR review.

Ok Nick, just removed the comments I added before. Thanks for the tips about the new branch, I will create one.

2023-02-03 13:00 UTC, nmcharlton approved these changes

2023-02-04 13:46 UTC, merged