Showing Sub-organizations as dropdown from the organization of a Grower
Greenstand/treetracker-admin-client pull request #1124
Opened 2023-10-28 21:09 UTC by samwel141

## Description
managed to show the dropdown list of sub-organizations associated with an organization of a Grower

**Issue(s) addressed**
Issue number 886 under progress to be resolved

**What kind of change(s) does this PR introduce?**

- [x ] Enhancement
- [ ] Bug fix
- [ ] Refactor

**Please check if the PR fulfils these requirements**

- [x ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## Issue

**What is the current behavior?**

**What is the new behavior?**

now on checking an inline radio button the list of sub-organizations drops from organization name

## Breaking change

2023-11-24 20:57 UTC, gwynndp commented
@samwel141 

Off to a nice start!  Can you link to the issue that this PR resolves?  
I think there are some open questions to answer before we can fully resolve this.

- Do we want to show all the Sub-Orgs for the Organization on each grower, or only show the Organization and Sub-Orgs that they belong to
- For a better UX we may need a way to tell the difference between the Org/Sub-Orgs the grower belongs to and the rest, if we want to list them all there

In the meantime, there is a display problem with your current implementation. It is also displaying on the Grower Cards in a jumbled way.  See below:

<img width="1264" alt="Screenshot 2023-11-24 at 12 45 11 PM" src="https://github.com/Greenstand/treetracker-admin-client/assets/1761374/a1e87d6b-a6dd-48db-bd4e-6bd0d3ae57e8">

On the card we might just want to list all of the organizations as comma-separated values to keep it compact, rather than have a dynamic dropdown.

2023-11-24 20:58 UTC, gwynndp requested changes

2023-11-24 20:58 UTC, gwynndp commented on package.json
> +    "webpack": "^5.89.0",
Was this intended?  It shouldn't be necessary, but if you ran into a problem then we can create a separate issue for it.

2023-12-16 08:22 UTC, samwel141 commented
Hello, thank you so much for your consideration.
I was trying to solve this issue
https://github.com/Greenstand/treetracker-admin-client/issues/886 and my
concern is to know from you if that is what you wanted.
About the change fracturing the UI in cards, I'll work on it but it depends
on your reply to the above question.
Any change in the package.json file was not intended and will rectify it.

Regards,

On Fri, Nov 24, 2023 at 11:57 PM Gwynn Dandridge-Perry <
***@***.***> wrote:

> @samwel141 <https://github.com/samwel141>
>
> Off to a nice start! Can you link to the issue that this PR resolves?
> I think there are some open questions to answer before we can fully
> resolve this.
>
>    - Do we want to show all the Sub-Orgs for the Organization on each
>    grower, or only show the Organization and Sub-Orgs that they belong to
>    - For a better UX we may need a way to tell the difference between the
>    Org/Sub-Orgs the grower belongs to and the rest, if we want to list them
>    all there
>
> In the meantime, there is a display problem with your current
> implementation. It is also displaying on the Grower Cards in a jumbled way.
> See below:
> Screenshot.2023-11-24.at.12.45.11.PM.png (view on web)
> <https://github.com/Greenstand/treetracker-admin-client/assets/1761374/a1e87d6b-a6dd-48db-bd4e-6bd0d3ae57e8>
>
> On the card we might just want to list all of the organizations as
> comma-separated values to keep it compact, rather than have a dynamic
> dropdown.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Greenstand/treetracker-admin-client/pull/1124#issuecomment-1826080661>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A2PRQ42KOT22IMNCAPRUFO3YGEC5LAVCNFSM6AAAAAA6UKUM5GVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMRWGA4DANRWGE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-12-30 20:44 UTC, samwel141 commented
I have put everything clear in the UI can you give feedback on that also

2024-01-09 22:05 UTC, gwynndp commented
Looks much better.  If you remove your package.json and package-lock.json changes then I'll merge.

2024-01-10 22:13 UTC, samwel141 commented
Removed changes in the package.json and package-lock.json, so it is now clear.

2024-01-12 21:05 UTC, gwynndp approved these changes

2024-01-12 21:05 UTC, merged