feat: improve consistency between Tree Detail and Planter Detail dialogs #10
Greenstand/treetracker-admin-client pull request #143
Opened 2021-08-08 21:41 UTC by chromium-52

Resolves #10

2021-08-09 21:38 UTC, nmcharlton requested changes
Fantastic work! Just a couple of comments on the changes.

Some other suggestions for adjacent changes:
- I think we can get rid of the slide up transition – it looks a little odd when placed next to the sliding drawer.
- Can we also not clear the capture on `handleClose` in `Verify.js`? That will give a smooth when closing the dialog.

2021-08-09 21:38 UTC, nmcharlton commented on src/components/CaptureDetailDialog.js
> +              <IconButton onClick={() => props.onClose()}>
Clicking the _Close_ button throws an exception:
> Uncaught TypeError: props.onClose is not a function

2021-08-09 21:38 UTC, nmcharlton commented on src/components/CaptureDetailDialog.js
> +          width={320}
I think we can make the capture image bigger now there's a bit more room for it.
We have three options, any of which would work well:

1. Dynamically calculate what size of image would fit in the space and request that using the `OptimizedImage` component
2. Drop `OptimizedImage` for the full-size image and just shrink the original image to fill the space
3. Set the `OptimizedImage` width to `600`

2021-08-14 05:49 UTC, chromium-52 commented
Thank you so much for the comments! I've made the above changes; please let me know if I misunderstood anything or if I can improve further!

2021-08-14 13:27 UTC, nmcharlton approved these changes
This is awesome! Great work @chromium-52

2021-08-14 13:27 UTC, merged