fix: make the verify and captures pages consistent
Greenstand/treetracker-admin-client pull request #152
Opened 2021-08-19 11:28 UTC by tranquanghuy0801

Resolves issue #51

2021-09-17 20:43 UTC, nmcharlton requested changes
Excellent work @tranquanghuy0801!
Just a few minor comments.

2021-09-17 20:43 UTC, nmcharlton commented on src/components/CaptureTable.js
> +      isFilterShown: false,
Let's make this `true` by default. The user is like to use the filter every time they visit the tool, but will still have a mechanism for hiding it if they need more space for the content.

2021-09-17 20:43 UTC, nmcharlton commented on src/components/CaptureTable.js
>      noSort: true,
I think sorting could be useful on `deviceIdentifier`

2021-09-17 20:43 UTC, nmcharlton commented on src/components/CaptureTable.js
>      noSort: true,
I think sorting could be useful on `planterIdentifier`

2021-09-17 20:43 UTC, nmcharlton commented on src/components/CaptureTable.js
> +    return capture[attr] ? speciesState[capture[attr]] : '--';
A minor point, but this will return `--` if `capture.speciesId===0`, which could be a valid value.

2021-09-17 20:43 UTC, nmcharlton commented on src/components/FilterTop.js
> +export const getVerificationStatus = (active, approved) => {
If this is a common utility being shared across components, it should be moved to a common location (e.g. under `src/utils/`). We shouldn't import a function from another component like this.

2021-09-17 20:48 UTC, nmcharlton requested changes

2021-09-17 20:48 UTC, nmcharlton commented on src/components/CaptureTable.js
>    },
Set this to `noSort: true,`
There's no `verificationStatus` attribute in the capture object, so it's not directly sortable using the LoopBack query.

2021-09-17 23:47 UTC, tranquanghuy0801 commented
@nmcharlton Thanks for the feedback. I have made the changes as you requested

2021-09-18 13:12 UTC, tranquanghuy0801 commented
@nmcharlton , I think the issue #110  relates to this. We already had UUID field in Capture Detail dialog. Do we need to put UUID field in the top filter as well?

2021-09-22 21:18 UTC, nmcharlton approved these changes
Awesome work, thanks @tranquanghuy0801!

2021-09-22 21:21 UTC, nmcharlton commented
> @nmcharlton , I think the issue #110 relates to this. We already had UUID field in Capture Detail dialog. Do we need to put UUID field in the top filter as well?

Let's get this PR merged and aligned with the @gwynndp's refactor, then address #110 under a separate PR.

2021-09-23 23:27 UTC, tranquanghuy0801 commented
@nmcharlton , do I have to push more commits to resolve these conflicts?

2021-09-24 19:02 UTC, nmcharlton commented
> @nmcharlton , do I have to push more commits to resolve these conflicts?

It would be great if you're able to resolve the conflicts and push the result.
It's likely to take some time and care to get right - let me or @gwynndp know if you want some help.

2021-09-25 01:44 UTC, dadiorchen commented
@tranquanghuy0801 you can merge master into your branch and resolve conflicts and push

2021-09-25 02:54 UTC, tranquanghuy0801 commented
> @tranquanghuy0801 you can merge master into your branch and resolve conflicts and push

yeah, I am doing that.

2021-09-27 21:08 UTC, nmcharlton requested changes
Just a couple of merge issues

2021-09-27 21:08 UTC, nmcharlton commented on src/components/FilterTop.js
> -  const [uuid, setUUID] = useState(filter?.uuid || '');
Looks like the UUID change has been accidentally removed in the merge.

2021-09-27 21:08 UTC, nmcharlton commented on src/components/FilterTop.js
> -  const defaultOrgList = userHasOrg
This block needs to stay

2021-09-27 21:08 UTC, nmcharlton commented on src/components/FilterTop.js
> -                /* {!userHasOrg && ( }*/
All the org changes here need to stay in

2021-09-28 11:21 UTC, nmcharlton approved these changes
Great work 😎

2021-09-28 11:21 UTC, merged