feat: add multi-select dropdown for verification status of captures f…
Greenstand/treetracker-admin-client pull request #212
Opened 2021-11-25 14:59 UTC by tranquanghuy0801

## Description

Add Multi-select dropdown for Verification Status field in filter of Captures page

**Issue(s) addressed**
- Resolves #114 

**What kind of change(s) does this PR introduce?** 
- [x] Enhancement
- [ ] Bug fix
- [ ] Refactor

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## Issue

**What is the current behavior?**

The current design is a single dropdown menu for Verification Status field in Captures page

**What is the new behavior?**

The new design is a multi-select dropdown menu for Verification Status field in Captures page

## Breaking change
**Does this PR introduce a breaking change?** 

No breaking changes

## Other useful information

## Video Screenshot 

https://user-images.githubusercontent.com/29462498/143463655-7004774c-67bd-4376-a601-d3e6d4994ca7.mov

2021-12-12 20:55 UTC, nmcharlton requested changes

2021-12-12 20:55 UTC, nmcharlton commented on src/components/CaptureFilter.js
> +  function handleChangeActiveApproved(value) {
Unfortunately, this logic doesn't cover all possible combinations, and it's hard to follow what it's trying to do.
If _Approved_ and _Rejected_ are selected, everything (including _Awaiting Verification_) is included.

I'd suggest replacing `approved` and `active` in the filter model with these Verification States and only converting when the API query is constructed.
You will need to apply an `and` clause to the query object: https://loopback.io/doc/en/lb4/Where-filter.html#and--or

2022-01-06 20:54 UTC, nmcharlton commented
Hey @tranquanghuy0801. What's the latest on this PR? I notice you've pushed a couple of commits, but the problem with the logic is still present. Do you need some help working out what needs to change?

2022-01-07 01:38 UTC, tranquanghuy0801 commented
@nmcharlton The latest PR is just resolving some issues when pulling the updates from master branch. I understand how to fix and am working on this. Sorry for the delay.

2022-01-08 11:12 UTC, tranquanghuy0801 commented
@nmcharlton I have updated the code as you suggested. Now you can check my work. Thanks

2022-01-08 14:49 UTC, nmcharlton requested changes
@tranquanghuy0801 This seems to be working well, but I don't think it makes sense to be able to select none of the values (and get zero results).

Having nothing selected should return the same results as having all values selected (i.e., all captures).

2022-01-08 15:19 UTC, tranquanghuy0801 commented
> @tranquanghuy0801 This seems to be working well, but I don't think it makes sense to be able to select none of the values (and get zero results).
> 
> Having nothing selected should return the same results as having all values selected (i.e., all captures).

Yeah I intended to show all results when the verification status is empty. It turned out it has an error in the function onHandleChange the value of these statues, which causes the incorrect data on the table. Now I fix that one.

2022-01-09 21:33 UTC, nmcharlton reviewed
Thanks @tranquanghuy0801!

2022-01-09 21:33 UTC, nmcharlton approved these changes

2022-01-09 21:33 UTC, merged