Earnings api integration
Greenstand/treetracker-admin-client pull request #226
Opened 2021-12-02 06:38 UTC by Mloweedgar

## Description

Integrates Earnings UI with the earnigs API

**Issue(s) addressed**

- Resolves #179 

**What kind of change(s) does this PR introduce?**

- [ ] Enhancement
- [ ] Bug fix
- [ ] Refactor

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## Issue

**What is the current behavior?**
Earnings Table displays dummy data

**What is the new behavior?**
Earning table displays data returned from earnings API

## Breaking change

**Does this PR introduce a breaking change?**

NO breaking changes

## Other useful information

2021-12-13 04:28 UTC, pieroapretto commented on src/components/Routers.js
> +                      key={`route_${i}`}
Is using index to set `key` values good practice?

2021-12-15 07:06 UTC, pieroapretto commented on src/components/Routers.js
> +                      key={`route_${i}`}
Sure. However, using index values to generate unique keys could negatively impact performance and may cause issues with component state according to React [documentation](https://reactjs.org/docs/lists-and-keys.html).

2021-12-20 18:02 UTC, Siddhant-K-code approved these changes
LGTM 🎉 

Thanks ❤️

2021-12-20 18:02 UTC, Siddhant-K-code commented on .env.development
> +REACT_APP_EARNINGS_API_MAPPING=/earnings
@Mloweedgar Just add this line

2021-12-20 18:03 UTC, Siddhant-K-code requested changes
Fix Merge Conflicts & solve UnResolved

2021-12-21 23:09 UTC, nmcharlton commented on src/utilities/index.js
> +export const covertDateStringToHumanReadableFormat = (
I'd suggest using or expanding the existing utility functions in `src/common/locale.js` to achieve this.
That way, the user will always see a format appropriate to their locale.

2021-12-21 23:11 UTC, nmcharlton commented
I've added a few more comments, but I'm happy to merge the PR and raise separate issues to capture them, especially if they require significant effort.

2021-12-23 05:57 UTC, Mloweedgar commented
Thanks @nmcharlton , I see they are minor, I am going to address them here. I real do appreciate your feedback, thank you very much.

2021-12-28 17:48 UTC, nmcharlton commented
Can you rename the handler functions and class names to match the new RESET button labels?

2021-12-29 06:56 UTC, Mloweedgar commented
@nmcharlton I have updated the handler functions by renaming the `Cancel` word to `Reset`

2021-12-29 08:01 UTC, nmcharlton approved these changes

2021-12-29 08:02 UTC, merged