feat: add options for any-tag-set and tag-not-set
Greenstand/treetracker-admin-client pull request #227
Opened 2021-12-02 14:52 UTC by bstetzer32

## Description

Added ability to filter by trees that have any tag set by passing in an id of "0" (see [treetracker-admin-api PR #608](https://github.com/Greenstand/treetracker-admin-api/pull/608)). 
**Issue(s) addressed**

- Resolves #199

**What kind of change(s) does this PR introduce?**

- [x] Enhancement

**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines

## Issue

**What is the current behavior?**
Users only have the ability to filter by either tag-not-set or by an individual tag.

**What is the new behavior?**
Users now have the ability to filter by any-tag-set as well as tag-not-set or by an individual tag. 

## Breaking change

**Does this PR introduce a breaking change?**
No

## Other useful information
I included 2 possible options for a divider: one using the renderOption prop on AutoComplete to apply a class to the option if it is any-tag-set, and the other using a CSS style for #tag-option-1.

2021-12-08 21:21 UTC, nmcharlton requested changes
Hi @bstetzer32, sorry for the delay in reviewing this – I've got quite a backlog to work through and time is limited.

I've noticed that the API is returning duplicate captures.
If you filter Approved captures with Any tag set, you'll see capture 951788 twice.
This is also reflected in the capture counts which don't quite add up.
I'll raise an issue against the API that we'll need to fix.

2021-12-08 21:21 UTC, nmcharlton commented on src/components/FilterTop.js
> +                // Option B for divider
If Material UI doesn't provide a good way of adding dividers, let's go without for now.

2021-12-13 04:23 UTC, pieroapretto commented on src/components/FilterTop.js
> +    // tagDecorator: {
Is this comment needed?

2022-01-04 20:31 UTC, nmcharlton approved these changes
Looking good

2022-01-04 20:35 UTC, merged