Id update
Greenstand/treetracker-admin-client pull request #262
Opened 2022-01-01 21:52 UTC by gwynndp

## Description

Make Stakeholder tool more user friendly.

**Issue(s) addressed**
- get unlinked stakeholders based on the current stakeholder detail and the logged in account
- format the Add form: add initial state, format fields, close modal on success
- format Filter form: add initial state, format fields
- optimize linking and unlinking state changes
- add state for count

**What kind of change(s) does this PR introduce?**

- [x] Enhancement

**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## Breaking change

**Does this PR introduce a breaking change?**

- [x] No breaking changes

## Other useful information

2022-01-12 21:56 UTC, nmcharlton reviewed
I've made a start on the review but have a little way to go.
Looking great so far though!

2022-01-12 21:56 UTC, nmcharlton commented on src/context/AppContext.js
> +// import EarningsView from '../views/EarningsView/EarningsView';
We need to reinstate all of the commented out tools before merging.

2022-01-12 21:56 UTC, nmcharlton commented on src/context/AppContext.js
> +          // POLICIES.LIST_STAKEHOLDERS,
New policies have been assigned to the _Stakeholder Manager_ role in the dev, test and prod databases and can be assigned to users.

2022-02-03 20:14 UTC, nmcharlton requested changes
Sorry, I added a few comments a while ago but I looks like I didn't submit them.

2022-04-03 18:50 UTC, gwynndp commented on src/api/stakeholders.js
> +const STAKEHOLDER_API = process.env.REACT_APP_STAKEHOLDER_API_ROOT;
I've added the current version there now

2022-04-06 00:32 UTC, gwynndp commented on src/components/Stakeholders/Add.js
> +      name: 'Grower',
Good question!  I can change it to Person to match the database types now

2022-04-06 00:43 UTC, gwynndp commented
@nmcharlton I've pushed through an update with your requested changes only.  Let's merge this so that I can integrate it with the next PR.

2022-04-06 05:58 UTC, nmcharlton requested changes

2022-04-06 05:58 UTC, nmcharlton commented on .env.development
> +<<<<<<< HEAD
Just need to remove these conflict markers and any duplicate entries.

2022-04-06 15:53 UTC, gwynndp commented
Whoops!  & Thank you!

On Tue, Apr 5, 2022 at 10:58 PM Nick Charlton ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In .env.development
> <https://github.com/Greenstand/treetracker-admin-client/pull/262#discussion_r843494896>
> :
>
> > @@ -6,10 +6,22 @@ REACT_APP_QUERY_API_ROOT=https://dev-k8s.treetracker.org/query
>  REACT_APP_REPORTING_API_ROOT=https://dev-k8s.treetracker.org/reporting
>  REACT_APP_REGION_API_ROOT=https://dev-k8s.treetracker.org/regions
>  REACT_APP_TREETRACKER_API_ROOT=https://dev-k8s.treetracker.org/treetracker
> +<<<<<<< HEAD
>
> Just need to remove these conflict markers and any duplicate entries.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Greenstand/treetracker-admin-client/pull/262#pullrequestreview-932862241>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AANOAXSYJZJZ5M3D3HEPYV3VDURZBANCNFSM5LC42OXQ>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2022-04-10 17:24 UTC, nmcharlton commented on src/api/apiUtils.js
> +  console.log('handleError', error);
If this logging needs to be here, it should use `log.debug()` or similar.

2022-04-10 17:24 UTC, nmcharlton commented on src/api/stakeholders.js
> +      query += `/${id}?isRelation=${false}&owner_id=${orgId}`;
Case in API parameters should be consistent. I'd expect `isRelation` to be `is_relation`.

2022-04-10 17:24 UTC, nmcharlton commented on src/context/AppContext.js
> +          POLICIES.APPROVE_TREE,
I don't think `APPROVE_TREE` belongs here.

2022-04-10 23:41 UTC, gwynndp commented
@nmcharlton I noticed you weren't on the [other PR](https://github.com/Greenstand/treetracker-admin-client/pull/340), so I added you.

The changes you requested here aren't in the other PR but I'll rebase there once this is merged.

2022-05-09 22:18 UTC, closed without merging