Fix 233
Greenstand/treetracker-admin-client pull request #273
Opened 2022-01-08 11:18 UTC by tranquanghuy0801

## Description

Improve capture multi-selection UX in for batch verification

**Issue(s) addressed**

- Resolves #233 

**What kind of change(s) does this PR introduce?**

- [X] Enhancement
- [ ] Bug fix
- [ ] Refactor

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## Issue

**What is the current behavior?**

**What is the new behavior?**

## Breaking change

**Does this PR introduce a breaking change?**

## Other useful information

2022-01-20 21:18 UTC, nmcharlton requested changes

2022-01-20 21:18 UTC, nmcharlton commented on src/context/VerifyContext.js
> +  //   } else if (isShift) {
Can we try to keep the shift-click functionality working?

2022-01-20 21:18 UTC, nmcharlton commented on src/components/SidePanel.js
> +            Unselect All
I think "Select None" might be better

2022-01-24 05:14 UTC, tranquanghuy0801 commented
@nmcharlton  I have updated the code as your suggestions. The only thing I did not change is that I still use the `parseInt()` in the function `getCaptureSelectedArr` in `VerifyContext` as the `Object.keys()` only accepts keys as strings, thus returning array of strings and we need array of integers for processing the `approveAll`.

2022-02-03 20:22 UTC, nmcharlton requested changes

2022-02-03 20:22 UTC, nmcharlton commented on src/context/VerifyContext.js
> +      setCaptureImagesSelected({
You need to call `setCaptureImageAnchor(captureId);` here, otherwise shift-click doesn't work properly.

2022-02-03 20:22 UTC, nmcharlton commented on src/components/SidePanel.js
> +      let captureSelected = {};
@tranquanghuy0801 This one need to be addressed to.

2022-02-19 17:57 UTC, nmcharlton approved these changes

2022-02-19 18:02 UTC, merged