feat: Loading Indicator On Captures Page
Greenstand/treetracker-admin-client pull request #305
Opened 2022-01-19 12:14 UTC by mitia-anah

## Description

- Added loading indicator to captures page. While the captures table is loading, the loading indicator is displayed. 

**Issue(s) addressed**

- Resolves #https://github.com/Greenstand/treetracker-admin-client/issues/297

**What kind of change(s) does this PR introduce?**

- [ ] Enhancement
- [ ] Bug fix
- [ ] Refactor

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## Issue

**What is the current behavior?**
- It takes several seconds for any records to appear in the Captures table,

**What is the new behavior?**
- The loading indicator is displayed to give the user feedback that loading has not been completed yet.

## Breaking change

**Does this PR introduce a breaking change?**

## Other useful information

2022-01-20 04:13 UTC, TANguyen1893 reviewed
Would it be easy to add tests to ensure the changes that are made will not break anything?

2022-01-22 10:52 UTC, nmcharlton commented
@mitia-anah Please can you rebase or merge the latest Greenstand master branch into your feature branch?

2022-01-26 21:47 UTC, nmcharlton requested changes
I've merged in changes from another PR that got lost, so you'll need to do `git pull origin` again before making changes.

2022-01-26 21:47 UTC, nmcharlton commented on src/components/Captures/CaptureTable.js
> +          {captures.length === 0 ? (
Unfortunately, this isn't quite enough. There may be occasions when zero captures match the filters, so we want to show an empty list.
Instead, we will need to add an `isLoading` boolean flag to CapturesContext that tracks whether a Captures load is in progress.

2022-02-19 17:28 UTC, nmcharlton requested changes

2022-02-19 17:28 UTC, nmcharlton commented on src/components/Captures/CaptureTable.js
> +      return isLoading;
Nothing uses the return value from this function, so this doesn't do anything.
The `isLoading` flag should be set to `true` before the API is called and `false` when the response is received. See  VerifyContext for guidance:
https://github.com/Greenstand/treetracker-admin-client/blob/4498a21d77b7c02ab1647248df303a603a5da198/src/context/VerifyContext.js#L142

This flag should then be used in CapturesTable to determine whether to show the loading indicator.

2022-02-19 17:34 UTC, nmcharlton commented on src/components/Captures/CaptureTable.js
> +              style={{ position: 'relative', left: '300%', bottom: '-179px' }}
Move the style details to CaptureTable.styles.js as a new class that is referenced with an attribute like `className={classes.loadingIndicator}`.

2022-02-19 17:34 UTC, nmcharlton commented on src/components/Captures/CaptureTable.js
> +              style={{ position: 'relative', left: '300%', bottom: '-179px' }}
This positioning seems odd. Take a look at how `CircularProgress` is positioned in other admin panel tools.

2022-02-19 17:35 UTC, nmcharlton commented on src/components/Captures/CaptureTable.js
> +          {captures.length === 0 ? (
This should be `{isLoading ? (`

2022-03-01 20:44 UTC, nmcharlton approved these changes
I've moved things around a little – it's a good idea for the Context to manage the loading state and the Table to just read it.

2022-03-01 20:52 UTC, merged