Fix bug with DistanceTo
Greenstand/treetracker-admin-client pull request #438
Opened 2022-02-24 03:13 UTC by gwynndp

## Description

Capture match wasn't loading because of a but with DistanceTo.

It was referencing .lat and .lon when the properties are now .latitude and .longitude
And the values were strings when the calculation needed floats

**Issue(s) addressed**
- no issue

**What kind of change(s) does this PR introduce?**

- [ ] Enhancement
- [x] Bug fix
- [ ] Refactor

**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

2022-02-24 08:45 UTC, nmcharlton requested changes
From my testing it looked like the missing `latitude` and `longitude` values come from the candidate _tree_. If it has no captures, we use the tree itself as a capture (`lat`,`lon`,`created_at`,`image_url`).

We need the API to be consistent, or to always populate the captures for candidate trees.

Also, I'd suggest fixing the checks for `lat1 === 'undefined'` etc. to be `lat1 === undefined` so we catch those instances and don't display NaN (which is invariably confusing for users).

2022-02-24 23:30 UTC, ZavenArra approved these changes

2022-02-24 23:58 UTC, gwynndp commented
@nmcharlton Thanks, I missed that the properties were named differently.  See if this works for the moment.

2022-02-25 06:41 UTC, nmcharlton approved these changes
Looks good

2022-02-25 06:41 UTC, merged