feat: Added tooltip for growers, captures and verify
Greenstand/treetracker-admin-client pull request #649
Opened 2022-04-18 09:51 UTC by mayankbucha

## Description

Clickable hover tooltip for growers, captures and verify.

**Issue(s) addressed**

- Resolves #408 

**What kind of change(s) does this PR introduce?**

- [x] Enhancement
- [ ] Bug fix
- [ ] Refactor

**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## Issue

**What is the current behavior?**

No tooltip for grower, capture and verify.

**What is the new behavior?**
Grower tooltip
![image](https://user-images.githubusercontent.com/47553721/163789865-7f5cc19f-bf4b-42ba-880a-2360db859d3c.png)

Capture tooltip
![image](https://user-images.githubusercontent.com/47553721/163789995-7ae0bea6-fc1a-49c7-8f95-539817cbd039.png)

Verify tooltip
![image](https://user-images.githubusercontent.com/47553721/163791130-2932b051-d33f-433e-ad63-f8dda7750304.png)

## Breaking change

**Does this PR introduce a breaking change?**
No

2022-04-18 14:17 UTC, nmcharlton requested changes
This is looking really good!
I've rebased the branch to resolve the conflicts and corrected a couple of typos, so you may need to pull before making additional changes.

I'm a little concerned about how distracting the tooltips could be on the Verify tool, and they may get in the way if the user is selecting multiple captures in quick succession.
Can we introduce a longer delay before showing the tooltip so that the user has to rest for a moment on the capture? I think that could help.

Can we add the Capture Details (Verify) tooltip to the captures on the right-hand side of the Capture Matching tool (https://dev-admin.treetracker.org/capture-matching)?

2022-04-18 14:17 UTC, nmcharlton commented on src/components/VerifyTooltip.js
> +const VerifyTooltip = ({ capture, showCaptureClick }) => {
I'd suggest renaming this component `CaptureDetailTooltip` since it will be used in a few different tools as a quick-look for the capture details.

2022-04-23 19:10 UTC, mayankbucha commented
Hi @nmcharlton,
For Verify, I have added delay of 1 sec for tooltip to appear.
For CandidateImages in CaptureMatching view, how can we access captureId, planterId, planterIdentifier and note properties.

2022-04-25 20:09 UTC, nmcharlton commented
@mayankbucha Ah yes, sorry. We can't easily join up the Capture Matching tool and Capture details just yet, as Capture Matching uses the new treetracker-api with a different ID system.

We will address this soon by moving Verify and Captures to the new API. We can cover the Capture Matching tooltips under a separate issue.

2022-05-02 12:57 UTC, nmcharlton commented
@mayankbucha Have you pushed your latest changes?

2022-05-03 17:48 UTC, mayankbucha commented
@nmcharlton sorry for the late response. I have pushed the changes now.

2022-05-04 19:45 UTC, nmcharlton requested changes
A couple more suggestions.
Also, if you click the tooltip to show the details (an awesome feature) and leave the cursor where it is, the tooltip seems to reappear. This is a minor thing, but would be nice to fix:

https://user-images.githubusercontent.com/5558838/166813700-b9537d1a-b889-426f-8c53-657bf13fc38c.mov

2022-05-17 19:28 UTC, merged