Add Capture Detail to Capture Match
Greenstand/treetracker-admin-client pull request #751
Opened 2022-07-19 06:22 UTC by gwynndp

## Description

- add Capture Detail to Capture Match Image
- fix bug with Country and DistanceTo that would prevent page from loading next Capture Image because of too many re-renders

**Issue(s) addressed**

- Resolves #issue_number

**What kind of change(s) does this PR introduce?**

- [x] Enhancement
- [x] Bug fix
- [ ] Refactor

**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

2022-07-19 20:07 UTC, nmcharlton requested changes

2022-07-19 20:07 UTC, nmcharlton commented on src/api/treeTrackerApi.js
> +      const query = `${CAPTURE_MATCH_API}/captures/${id}`;
It's a bit confusing to call this `CAPTURE_MATCH_API` here. It masks that we're just using the treetracker-api to query captures.

2022-07-21 20:43 UTC, nmcharlton reviewed
@gwynndp Can you take a look at the failing tests?

2022-07-21 21:50 UTC, gwynndp commented
> @gwynndp Can you take a look at the failing tests?

Should I do the React 18 updates? I don't think the updates would be backward compatible, so would every user running the admin client be updated to react 18 when they work on it?

2022-07-24 20:34 UTC, merged